artifact_uri: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/mlflow/482896656913041974/c67565b6e0544c8fb83b15803eb41da1/artifacts
end_time: 1766750116156
entry_point_name: ''
experiment_id: '482896656913041974'
lifecycle_stage: active
run_id: c67565b6e0544c8fb83b15803eb41da1
run_name: red_cube_ultra_simple
source_name: ''
source_type: 4
source_version: ''
start_time: 1766750088940
status: 3
tags: []
user_id: nathan
