artifact_uri: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/mlflow/899706621568372456/a7557101f54e4c7084cad8a1b70c48ed/artifacts
end_time: 1766751699383
entry_point_name: ''
experiment_id: '899706621568372456'
lifecycle_stage: active
run_id: a7557101f54e4c7084cad8a1b70c48ed
run_name: red_cube_ultra_simple
source_name: ''
source_type: 4
source_version: ''
start_time: 1766751622091
status: 3
tags: []
user_id: nathan
