artifact_uri: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/mlflow/899706621568372456/d15c3ac1ad8347feabe38e080e8697ec/artifacts
end_time: 1766756872612
entry_point_name: ''
experiment_id: '899706621568372456'
lifecycle_stage: active
run_id: d15c3ac1ad8347feabe38e080e8697ec
run_name: red_cube_v_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1766756797691
status: 3
tags: []
user_id: nathan
