artifact_location: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/mlflow/482896656913041974
creation_time: 1766750088804
experiment_id: '482896656913041974'
last_update_time: 1766750088804
lifecycle_stage: active
name: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/detect
