artifact_uri: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/mlflow/899706621568372456/fc3a938b8913428a8db9cc8c0eb0e5cf/artifacts
end_time: 1766752134964
entry_point_name: ''
experiment_id: '899706621568372456'
lifecycle_stage: active
run_id: fc3a938b8913428a8db9cc8c0eb0e5cf
run_name: red_cube_ultra_simple
source_name: ''
source_type: 4
source_version: ''
start_time: 1766752088197
status: 3
tags: []
user_id: nathan
