artifact_uri: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/mlflow/899706621568372456/80f040bbc5d94507803c3d6cde01ebb3/artifacts
end_time: 1766752399636
entry_point_name: ''
experiment_id: '899706621568372456'
lifecycle_stage: active
run_id: 80f040bbc5d94507803c3d6cde01ebb3
run_name: red_cube_ultra_simple
source_name: ''
source_type: 4
source_version: ''
start_time: 1766752351739
status: 3
tags: []
user_id: nathan
