artifact_location: /home/nathan/Documents/GitHub/3d_edge_object_detection/runs/mlflow/0
creation_time: 1766695964204
experiment_id: '0'
last_update_time: 1766695964204
lifecycle_stage: active
name: Default
